### ISSUE TITLE
Wiki errors

### ISSUE THREAD

**Issue by arturekdev** [A248/DazzleConf#13]
I bug in the wiki.

Error: SnakeYamlConfigurationFactory.create (configClass, ConfigurationOptions.defaults (), yamlOptions)
Fix: new SnakeYamlConfigurationFactory <C> (configClass, ConfigurationOptions.defaults (), yamlOptions)

**Comment by A248** [comment]
Thanks for noticing. The first one I will fix - that's actually because the *create* method has been added to an (unreleased) new version. I guess I updated the documentation too quickly!

As for #2 - `reloadConfigData` is correct. That method comes from the superclass, ConfigurationHelper. I may change the example to use composition over inheritance, but for now, it uses inheritance.

**Comment by A248** [comment]
Fixed now, let me know if you find anything else

**Comment by A248** [comment]
I should mention - `ConfigurationHelper` is from version 1.2.0-SNAPSHOT, which isn't on Maven Central. You'll need to use our snapshots repository for it:

```
https://oss.sonatype.org/content/repositories/snapshots/
```

(ConfigurationHelper is, as the name implies, purely a boilerplate-reducing helper class. You can recreate it yourself if necessary or if you want to change the behavior.)
