### ISSUE TITLE
Add documentation on how to use file-loaded defaults

### ISSUE THREAD

**Issue by Artuto** [A248/DazzleConf#26]
Hello, could you add some docs on how to make the library load configuration defaults from a file (ex. a resource).

This is mentioned on the wiki but there aren't any examples.

Thanks!

**Comment by A248** [comment]
In truth, it works the same way as loading the configuration from the file-system.

Use the InputStream of your resource (Class#getResourceAsStream) together with ConfigurationFactory#load(InputStream).

------------------------------

Also, if you're wondering about ConfigurationHelper – you don't need to use ConfigurationHelper. Nearly everyone I have seen uses it, but it was never intended as the main entry point to the API; ConfigurationFactory is.

ConfigurationHelper is but a small wrapper around it which removes some of the boiler-plate logic i.e. "check if the file exists, if not, use default values and write config, otherwise load config".

**Comment by A248** [comment]
An example of how this works in practice has been added to the wiki:
https://github.com/A248/DazzleConf/wiki/The-two-ways-of-using-DazzleConf#example
